screen -d -m -S rl-5-5 Rscript code/record_linkage/jasa_eber_diag.R 5 5
screen -d -m -S rl-5-10 Rscript code/record_linkage/jasa_eber_diag.R 5 10
screen -d -m -S rl-5-15 Rscript code/record_linkage/jasa_eber_diag.R 5 15
screen -d -m -S rl-10-5 Rscript code/record_linkage/jasa_eber_diag.R 10 5
screen -d -m -S rl-10-10 Rscript code/record_linkage/jasa_eber_diag.R 10 10
screen -d -m -S rl-10-15 Rscript code/record_linkage/jasa_eber_diag.R 10 15
screen -d -m -S rl-30-5 Rscript code/record_linkage/jasa_eber_diag.R 30 5
screen -d -m -S rl-30-10 Rscript code/record_linkage/jasa_eber_diag.R 30 10
screen -d -m -S rl-30-15 Rscript code/record_linkage/jasa_eber_diag.R 30 15
screen -d -m -S rl-50-5 Rscript code/record_linkage/jasa_eber_diag.R 50 5
screen -d -m -S rl-50-10 Rscript code/record_linkage/jasa_eber_diag.R 50 10
screen -d -m -S rl-50-15 Rscript code/record_linkage/jasa_eber_diag.R 50 15