screen -d -m -S rl-5-5-1 Rscript code/record_linkage/geco_eber_diag.R 5 5 1
screen -d -m -S rl-5-10-1 Rscript code/record_linkage/geco_eber_diag.R 5 10 1
screen -d -m -S rl-5-15-1 Rscript code/record_linkage/geco_eber_diag.R 5 15 1
screen -d -m -S rl-5-5-2 Rscript code/record_linkage/geco_eber_diag.R 5 5 2
screen -d -m -S rl-5-10-2 Rscript code/record_linkage/geco_eber_diag.R 5 10 2
screen -d -m -S rl-5-15-2 Rscript code/record_linkage/geco_eber_diag.R 5 15 2
screen -d -m -S rl-5-5-3 Rscript code/record_linkage/geco_eber_diag.R 5 5 3
screen -d -m -S rl-5-10-3 Rscript code/record_linkage/geco_eber_diag.R 5 10 3
screen -d -m -S rl-5-15-3 Rscript code/record_linkage/geco_eber_diag.R 5 15 3