screen -d -m -S bma-5-5-1 Rscript code/capture_recapture/geco_bma.R 5 5 1
screen -d -m -S bma-5-10-1 Rscript code/capture_recapture/geco_bma.R 5 10 1
screen -d -m -S bma-5-15-1 Rscript code/capture_recapture/geco_bma.R 5 15 1
screen -d -m -S bma-5-5-2 Rscript code/capture_recapture/geco_bma.R 5 5 2
screen -d -m -S bma-5-10-2 Rscript code/capture_recapture/geco_bma.R 5 10 2
screen -d -m -S bma-5-15-2 Rscript code/capture_recapture/geco_bma.R 5 15 2
screen -d -m -S bma-5-5-3 Rscript code/capture_recapture/geco_bma.R 5 5 3
screen -d -m -S bma-5-10-3 Rscript code/capture_recapture/geco_bma.R 5 10 3
screen -d -m -S bma-5-15-3 Rscript code/capture_recapture/geco_bma.R 5 15 3